spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost:5433}/orderdb
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

server:
  port: ${PORT:8081}

app:
  temporal:
    address: ${TEMPORAL_ADDRESS:localhost:7233}
    namespace: default
    taskQueue: order-task-queue