spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost:5434}/inventorydb
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true   # run data.sql AFTER Hibernate DDL
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: always   # run data.sql each startup
